//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexxi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flexxi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;Fit&quot;:&quot;Passend&quot;,
        ///&quot;Original&quot;:&quot;Original&quot;,
        ///&quot;Ignore&quot;:&quot;Ignorieren&quot;,
        ///&quot;Acquisition&quot;:&quot;Aufnahme&quot;,
        ///&quot;proportional&quot;:&quot;proportional&quot;,
        ///&quot;Select a File&quot;:&quot;Wähle eine Datei&quot;,
        ///&quot;Display modified images&quot;:&quot;Fertige Bilder anzeigen&quot;,
        ///&quot;none&quot;:&quot;keine&quot;,
        ///&quot;Auto Detect&quot;:&quot;Automatisch erkennen&quot;,
        ///&quot;90° clockwise&quot;:&quot;90° im Uhrzeigersinn&quot;,
        ///&quot;90° anticlockwise&quot;:&quot;90° gegen den Uhrzeigersinn&quot;,
        ///&quot;Quality&quot;:&quot;Qualität&quot;,
        ///&quot;Maximum&quot;:&quot;Maximum&quot;,
        ///&quot;Size&quot;:&quot;Größe&quot;,
        ///&quot;Proportionally&quot;:&quot;Verhältnis&quot;,
        ///&quot;Flip Size for Portai Images&quot;:&quot;Drehe Größe für Portr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;Yes&quot;:&quot;Si&quot;,
        ///&quot;Loading Language Package, please wait&quot;:&quot;Cargando Idioma, por favor espere&quot;,
        ///&quot;hour&quot;:&quot;hora&quot;,
        ///&quot;hours&quot;:&quot;horas&quot;,
        ///&quot;minute&quot;:&quot;minuto&quot;,
        ///&quot;minutes&quot;:&quot;minutos&quot;,
        ///&quot;second&quot;:&quot;secundo&quot;,
        ///&quot;seconds&quot;:&quot;segundos&quot;,
        ///&quot;remaining&quot;:&quot;faltan&quot;,
        ///&quot;started&quot;:&quot;empezado&quot;,
        ///&quot;Ready with&quot;:&quot;Listo con&quot;,
        ///&quot;files&quot;:&quot;Archivos&quot;,
        ///&quot;Duration&quot;:&quot;Duración&quot;,
        ///&quot;Ready&quot;:&quot;Listo&quot;,
        ///&quot;The Image&quot;:&quot;La imagen&quot;,
        ///&quot;couldn\u0027t be written to&quot;:&quot;no se podria escribir&quot;,
        ///&quot;Is this file open in another program?&quot;:&quot;Esta abierto en otra programma?&quot;,
        ///&quot;The F [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartImage {
            get {
                object obj = ResourceManager.GetObject("StartImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
